paths:
  input_audio_dir: audios
  speech_segments_dir: speech_segments
  processed_audio_dir: audios_processed
  db_path: transcriptions/transcriptions.sqlite
  json_output: transcriptions/transcriptions.json

pipeline:
  interval_seconds: 60
  max_backoff_seconds: 300

whisper:
  model_size_or_path: large-v3
  device: cpu
  compute_type: int8
  language: fr
  beam_size: 1
  best_of: 1
  patience: 1.0
  condition_on_previous_text: false
  temperature: 0.0
  compression_ratio_threshold: 1.8
  log_prob_threshold: -0.9
  no_speech_threshold: 0.3
  banned_phrases:
    - "Merci."
    - "Sous-titrage ST' 501"
    - "Sous-titrage Société Radio-Canada"

vad:
  sample_rate: 16000
  threshold: 0.2
  min_speech_duration_ms: 1000
  min_silence_duration_ms: 1000
  speech_pad_ms: 500
